name: todo_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  intl: ^0.17.0
  logger: ^1.1.0
  freezed: ^2.1.0+1
  freezed_annotation: ^2.1.0
  json_annotation: ^4.6.0
  json_serializable: ^6.3.1
  uuid: ^3.0.6
  device_info_plus: ^4.0.1
  flutter_secure_storage: ^5.0.2
  drift: ^1.7.1
  sqlite3_flutter_libs: ^0.5.9
  path_provider: ^2.0.11
  path: ^1.8.1
  dio: ^4.0.6
  flutter_svg: ^1.1.2
  table_calendar: ^3.0.6
  firebase_crashlytics: ^2.8.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.2.0
  drift_dev: ^1.7.0
  flutter_lints: ^2.0.0
  lints: ^2.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/app_icons/
