name: todo_app
description: Get your things done with this todo app!

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  intl: ^0.17.0
  logger: ^1.1.0
  freezed: ^2.1.0+1
  freezed_annotation: ^2.1.0
  json_annotation: ^4.6.0
  json_serializable: ^6.3.1
  uuid: ^3.0.6
  device_info_plus: ^4.0.1
  flutter_secure_storage: ^6.0.0
  drift: ^1.7.1
  sqlite3_flutter_libs: ^0.5.9
  path_provider: ^2.0.11
  path: ^1.8.1
  dio: ^4.0.6
  flutter_svg: ^1.1.2
  table_calendar: ^3.0.6
  firebase_crashlytics: ^2.8.6
  flutter_bloc: ^8.0.1
  bloc: ^8.1.0
  equatable: ^2.0.3
  bloc_concurrency: ^0.2.0
  android_id: ^0.0.7
  firebase_remote_config: ^2.0.16
  firebase_analytics: ^9.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  build_runner: ^2.2.0
  drift_dev: ^1.7.0
  flutter_lints: ^2.0.0
  lints: ^2.0.0
  device_preview: ^1.1.0
  bloc_test: ^9.1.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/app_icons/
