name: ToDo App release

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          
      - name: Check version
        run: flutter --version

      - name: Install dependencies
        run: flutter pub get

      - name: Build APK
        run: flutter build apk --split-per-abi lib/main_prod.dart --flavor prod

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
            name: todo-arm64-v8a.apk
            path: build/app/outputs/apk/prod/release/app-prod-arm64-v8a-release.apk
            
      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
            name: todo-armeabi-v7a.apk
            path: build/app/outputs/apk/prod/release/app-prod-armeabi-v7a-release.apk
            
      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
            name: todo-x86_64.apk
            path: build/app/outputs/apk/prod/release/app-prod-x86_64-release.apk

      - name: Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1.2.1
        with:
            appId: ${{secrets.FIREBASE_APP_ID}}
            token: ${{secrets.FIREBASE_TOKEN}}
            file: build/app/outputs/apk/prod/release/app-prod-arm64-v8a-release.apk

      - name: Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1.2.1
        with:
            appId: ${{secrets.FIREBASE_APP_ID}}
            token: ${{secrets.FIREBASE_TOKEN}}
            file: build/app/outputs/apk/prod/release/app-prod-armeabi-v7a-release.apk

      - name: Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1.2.1
        with:
            appId: ${{secrets.FIREBASE_APP_ID}}
            token: ${{secrets.FIREBASE_TOKEN}}
            file: build/app/outputs/apk/prod/release/app-prod-x86_64-release.apk
